### ISSUE TITLE
Validate mqtt.server

### ISSUE THREAD

**Issue by MrTreeBark** [timotto/ardumower-modem#1]
Hi! Keine Ahnung ob das hier hingehört^^
Ich habe deine .bin auf mein ESP32 gespielt.
Beim kompilieren hängt er sich ohne Fehler leider bei mir auf, obwohl ich alle Bibliotheken
eingepflegt habe. Er ist dann einfach Stuck und macht nix.

Die grundlegende Konfiguration über HTTP hat geklappt, 
jedoch die BT Funktion und MQTT habe ich nicht hinbekommen.
Über WLAN funktioniert die Sunray-App nachwievor, alle Daten da, aber nur wenn MQTT Disabled.

Wenn ich den Host für mqtt als IP eingebe bekomme ich einen Error: "Validate mqtt.server"
Dieses Feld nimmt nur Buchstaben? 
Probiert: IP, IP:PORT, mqtt://IP..

Ist bei der Ardumower Sunray Firmware noch etwas an Konfigurationen zu beachten?
Wär super wenn BT und MQTT bei mir funktionieren würden.

Bist du auch als timotto im Forum zu finden?
Grüße.

**Comment by timotto** [comment]
Hi! Die GitHub Issues sind der perfekte Ort für Probleme mit der Modem Firmware.

Die Firmware verweigert IP Adressen in der MQTT Server URL, das ist selbstverständlich [ein Bug](#2). Hätte ich mich schon um [sprechende Fehlermeldungen](#3) gekümmert, wäre mir der vielleicht schon früher aufgefallen ;-) Das sollte ich am Wochenende repariert haben.

Die Bluetooth Problemen [habe ich erwartet](https://forum.ardumower.de/threads/ardumower-esp-firmware-mit-mqtt-homeassistant-und-prometheus.24496/). Die Probleme beim kompilieren allerdings nicht. Im Forum findest du mich unter `tim`. Würde mich freuen, wenn wir das alles zusammen lösen können! Meld dich mal im Forum!

**Comment by timotto** [comment]
depends on [#2] and [#3]
