### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by HSchoch** [timotto/ardumower-modem#4]
Hi i get compiler errors:

`:\Users\holge\AppData\Local\Temp\arduino_build_901575\core\core.a(main.cpp.o):(.literal._Z8loopTaskPv+0x8): undefined reference to `setup()'
C:\Users\holge\AppData\Local\Temp\arduino_build_901575\core\core.a(main.cpp.o):(.literal._Z8loopTaskPv+0xc): undefined reference to `loop()'
C:\Users\holge\AppData\Local\Temp\arduino_build_901575\core\core.a(main.cpp.o): In function `loopTask(void*)':
C:\Users\holge\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32/main.cpp:18: undefined reference to `setup()'
C:\Users\holge\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32/main.cpp:21: undefined reference to `loop()'
collect2.exe: error: ld returned 1 exit `status``

**Comment by timotto** [comment]
It looks like you're trying to compile from incomplete source code. If just want to use the ArduMower Modem and don't plan to modify the source I suggest you try the [modem_install Sketch](https://github.com/timotto/ardumower-modem/blob/main/util/modem_install/modem_install.ino) from the `util/modem_install` folder to install a pre-compiled binary.

**Comment by HSchoch** [comment]
Hallo,
habe ich gemacht. Leider funktioniert der WLAN nicht.  
Serielle Ausgabe:

18:15:40.559 -> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
18:15:40.607 -> configsip: 0, SPIWP:0xee
18:15:40.607 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
18:15:40.607 -> mode:DIO, clock div:1
18:15:40.607 -> load:0x3fff0018,len:4
18:15:40.607 -> load:0x3fff001c,len:1216
18:15:40.607 -> ho 0 tail 12 room 4
18:15:40.607 -> load:0x40078000,len:10944
18:15:40.607 -> load:0x40080400,len:6388
18:15:40.607 -> entry 0x400806b4
18:15:40.985 -> Time sync.....................................................................................................................

Und jetzt geht es nicht weiter. Kein WiFi Access Point..
