### ISSUE TITLE
MQTT Port

### ISSUE THREAD

**Issue by HSchoch** [timotto/ardumower-modem#5]
Hallo,
wie kann man einen Port für den MQTT Server mitgeben?
Server:Port funktioniert nicht.

<vielen Dank

**Comment by timotto** [comment]
Der MQTT Port ist zur Zeit fix `1883`, es geht auch nur `mqtt` und kein `mqtts`. Brauchst du einen anderen Port? Ich nehm das mal als feature request auf.

**Comment by timotto** [comment]
In version 1.2.0 kannst du jetzt den Port in der MQTT Server URL frei konfigurieren, z.B. `server:port` oder `mqtt://server:port`.

**Comment by HSchoch** [comment]
Vielen Dank, werde es mal testen

**Comment by HSchoch** [comment]
Funktioniert super, Danke
