### ISSUE TITLE
Request: WiFi Repeater

### ISSUE THREAD

**Issue by jschwalbe** [timotto/ardumower-modem#7]
My esp32 (modem) has a nice antenna but the esp32 (xBee GPS) does *not* have a WiFi antenna.

It would be amazing if the `ardumower-modem` could act as a wifi relay.
In other words: connect to existing WiFi network (with the antenna) and then either rebroadcast the same wifi/password credentials, or broadcast a new SSID. This would allow my GPS esp32 to connect to SSID that's being broadcast by the mower instead of trying to reach across my yard (and through a metal box) without a WiFi antenna.

What do you think?
Thanks!

**Comment by timotto** [comment]
The esp32 does not support a WiFi repeater mode natively. I did find an implementation of a NAT router at https://github.com/martin-ger/esp32_nat_router . As far as I can see it's not a trivial piece of code I can just re-implement in the Arduino based ArduMower Modem code. But I'm always open to pull requests!

If you have a spare esp32 and don't need the external antenna for a Bluetooth connection you could run that esp32_nat_router code on the esp32 with the external antenna and run the modem on the spare esp32.
